---
title: 'Advent Of Code: 2021-03'
author: Leo Carlsson
date: "`r Sys.Date()`"
output: html_document
---

```{r setup}
suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
  library(glue)
  
  knitr::opts_chunk$set(echo = TRUE)
})

options(scipen = 9999999)
options(dplyr.summarise.inform = FALSE)
```

--- Data ---

```{r eval = FALSE}
# tanho63/aoc.elf
aoc.elf::aoc_get(day = 3, year = 2021)
```

```{r}
input <- readLines(here::here("2021/day-03-input.txt"))
```

--- Part 1 ---

```{r}
input_df <- tibble(input) %>% 
        separate(input, 
                 into = c("empty","first", "second", "third", "fourth", "fifth", "sixth",
                          "seventh", "eight", "nineth", "tenth", "eleventh", "twelveth"), 
                 sep = "") %>% 
        select(-empty) 

input_df %>% 
        summarise(across(everything(), DescTools::Mode)) %>% 
        unite(gamma_rate, sep="") %>% 
        mutate(gamma_rate = DescTools::BinToDec(gamma_rate)) %>% 
        bind_cols(
                input_df %>% 
                        summarise(across(everything(), DescTools::Mode)) %>% 
                        mutate(across(everything(), ~if_else(. == "1", "0", "1"))) %>% 
                        unite(epsilon_rate, sep="") %>% 
                        mutate(epsilon_rate = DescTools::BinToDec(epsilon_rate))
        ) %>% 
        mutate(power_consumption = gamma_rate*epsilon_rate)
```

--- Part 2 ---

```{r}
oxygen_generator_rating <- input_df
for (i in 1:length(oxygen_generator_rating)) {
        mode <- DescTools::Mode(as.numeric(pull(oxygen_generator_rating[,i])))
        if(is.na(mode)){
                mode <- 1
        } else if(length(mode)==2) {
                mode<-mode[2]
        } else{
                mode <- mode[1]
        }
        
        oxygen_generator_rating <- oxygen_generator_rating %>% 
                filter(oxygen_generator_rating[,i] == mode)
        if(nrow(oxygen_generator_rating) == 1) {
                break
        }
}


CO2_scrubber_rating <- input_df
for (i in 1:length(CO2_scrubber_rating)) {
        mode <- DescTools::Mode(as.numeric(pull(CO2_scrubber_rating[,i])))
        
        if(is.na(mode)){
                mode <- 0
        } else if(length(mode)==2) {
                mode<-mode[1]
        } else{
                mode <- mode[1]
                mode<- if_else(mode == 1, "0", "1")
        }
        
        CO2_scrubber_rating <- CO2_scrubber_rating %>% 
                filter(CO2_scrubber_rating[,i] == mode)
        if(nrow(CO2_scrubber_rating) == 1) {
                break
        }
}

oxygen_generator_rating %>% 
        unite(oxygen_generator_rating, sep="") %>% 
        mutate(oxygen_generator_rating = DescTools::BinToDec(oxygen_generator_rating)) %>% 
        bind_cols(CO2_scrubber_rating %>% 
                          unite(CO2_scrubber_rating, sep="") %>% 
                          mutate(CO2_scrubber_rating = DescTools::BinToDec(CO2_scrubber_rating))) %>% 
        mutate(life_support_rating = oxygen_generator_rating*CO2_scrubber_rating)
```