---
title: 'Advent Of Code: 2021-10'
author: "Tan Ho"
date: "2021-12-10"
output: html_document
---

```{r setup}
suppressPackageStartupMessages({
        library(tidyverse)
        library(here)
        library(glue)
        
        knitr::opts_chunk$set(echo = TRUE)
})

options(scipen = 9999999)
options(dplyr.summarise.inform = FALSE)
```

--- Data ---

```{r eval = FALSE}
aoc.elf::aoc_get(10)
```

```{r}
input <- readLines(here::here("2021/2021/day-10-input.txt"))

example <- c(
        "[({(<(())[]>[[{[]{<()<>>",
        "[(()[<>])]({[<{<<[]>>(",
        "{([(<{}[<>[]}>{[]{[(<()>",
        "(((({<>}<{<{<>}{[]{[]{}",
        "[[<[([]))<([[{}[[()]]]",
        "[{[{({}]{}}([{[{{{}}([]",
        "{<[[]]>}<{[{[{[]{()[[[]",
        "[<(<(<(<{}))><([]([]()",
        "<{([([[(<>()){}]>(<<{{",
        "<{([{{}}[<[[[<>{}]]]>[]]")
example
```

--- Part 1 ---

```{r}
remove_correct <- function(input) {
        remove <- c("\\(\\)" = "", "\\[\\]" = "", "\\{\\}" = "", "<>" = "")
        old <- input
        repeat {
                new = str_replace_all(old, remove)
                if(old == new) break
                old <- new
        }
        old
}

closure_detector <- function(input) {
        closure <- c("\\)", "\\]", "\\}", ">")
        res <- str_detect(input, closure)
        any(res)
}

remove_openers <- function(input) {
        openers <- c("\\(" = "", "\\{" = "", "\\[" = "", "<" = "")
        str_replace_all(input, openers)
}

extract_first <- function(input) {
        strsplit(input,"")[[1]][1]
}

give_points <- function(input) {
        values <- c("\\)" = "3", 
                    "\\]" = "57", 
                    "\\}" = "1197", 
                    ">" = "25137")
        as.integer(str_replace_all(input, values))
}

cleaned <- input %>% map_chr(remove_correct)
filter <- cleaned %>% map_lgl(closure_detector)

cleaned[filter] %>% 
        map_chr(remove_openers) %>% 
        map_chr(extract_first) %>% 
        map_int(give_points) %>% 
        sum()
```

--- Part 2 ---

```{r}
completer <- function(input) {
        input <- stringi::stri_reverse(input)
        replacement <- c("\\(" = "\\)", "\\{" = "\\}", "\\[" = "\\]", "<" = ">")
        str_replace_all(input, replacement)
}

completion_pointer <- function(input) {
        points <- c("\\)" = "1", "\\}" = "3", "\\]" = "2", ">" = "4")
        input <- str_replace_all(input, points)
        input <- strsplit(input,"")[[1]] %>% as.numeric()
        score <- 0
        for (i in 1:length(input)) {
                score <- score*5
                score <- score+input[i]
        }
        score
}

cleaned <- input %>% map_chr(remove_correct)
filter <- cleaned %>% map_lgl(closure_detector)
cleaned[!filter] %>% map_chr(completer) %>% 
        map_dbl(completion_pointer) %>% 
        median()
```


