---
title: 'Advent Of Code: 2021-11'
author: Leo Carlsson
date: "`r Sys.Date()`"
output: html_document
---

```{r setup}
suppressPackageStartupMessages({
        library(tidyverse)
        library(here)
        library(glue)
        
        knitr::opts_chunk$set(echo = TRUE)
})

options(scipen = 9999999)
options(dplyr.summarise.inform = FALSE)
```

--- Data ---

```{r eval = FALSE}
# tanho63/aoc.elf
aoc.elf::aoc_get(day = 11, year = 2021)
```

```{r}
input <- readLines(here::here("2021/day-11-input.txt")) %>% 
        strsplit("") %>% 
        unlist() %>% 
        as.integer() %>% 
        matrix(10, 10, byrow = TRUE)
input
example <- c("5483143223",
             "2745854711",
             "5264556173",
             "6141336146",
             "6357385478",
             "4167524645",
             "2176841721",
             "6882881134",
             "4846848554",
             "5283751526") %>% 
        strsplit("") %>% 
        unlist() %>%
        as.integer() %>% 
        matrix(10, 10, byrow = TRUE)
example
```

--- Part 1 ---
Using inspiration from Emil Hvitfeldts "around"-function
```{r}
#takes a index vector, where x[1] is the row number and x[2] is the col number.
matrix_around <- function(x) {
        row <- x[1]
        col <- x[2]
        row_id <- c(row - 1, row - 1, row - 1, row, row + 1, row + 1, row + 1, row)
        col_id <- c(col - 1, col, col + 1, col + 1, col + 1, col, col - 1, col - 1)
        subset <- !(row_id > size | col_id > size)
        cbind(row_id[subset], col_id[subset])
}

```



```{r}
zeros <- matrix(0, nrow = 4, ncol = 4)
increase_around <- function(matrix, x, y) {
    rows <- nrow(matrix)
    cols <- ncol(matrix)
    for (x_d in c(-1, 0, 1)) {
        for (y_d in c(-1, 0, 1)) {
            if (x_d != 0 || y_d != 0) {
                new_x <- x + x_d
                new_y <- y + y_d
                if (new_x >= 1 && new_x <= rows && new_y >= 1 && new_y <= cols) {
                    matrix[new_x, new_y] <- matrix[new_x, new_y] + 1
                }
            }
        }
    }
    return(matrix)
}

increase_around(zeros, 1, 3)
```











--- Part 2 ---

```{r}
size <- nrow(input)

around <- function(x) {
        row <- x[1]
        col <- x[2]
        row_id <- c(row - 1, row - 1, row - 1, row, row + 1, row + 1, row + 1, row)
        col_id <- c(col - 1, col, col + 1, col + 1, col + 1, col, col - 1, col - 1)
        subset <- !(row_id > size | col_id > size)
        cbind(row_id[subset], col_id[subset])
}

flashes <- 0

for (i in 1:100) {
        flashed <- matrix(FALSE, nrow = size, ncol = size)
        input <- input + 1
        
        repeat {
                new_flashes <- which((input * !flashed) > 9, arr.ind = TRUE)
                
                if (nrow(new_flashes) == 0) break
                
                flashed <- flashed | (input > 9)
                
                bursts <- map(seq_len(nrow(new_flashes)), ~around(new_flashes[.x, ])) |>
                        purrr::reduce(rbind)
                
                for (i in seq_len(nrow(bursts))) {
                        input[bursts[i, 1], bursts[i, 2]] <- input[bursts[i, 1], bursts[i, 2]] + 1
                }
        }
        input[flashed] <- 0
        flashes <- flashes + sum(flashed)
}

flashes

```

```{r}
which(LETTERS == "R")
which(ll <- c(TRUE, FALSE, TRUE, NA, FALSE, FALSE, TRUE)) #> 1 3 7
names(ll) <- letters[seq(ll)]
which(ll)
which((1:12)%%2 == 0) # which are even?
which(1:10 > 3, arr.ind = TRUE)
```


```{r}
modify(mtcars, 1)
```

```{r}
test <- split(mtcars, mtcars$cyl)
lapply(test, sum)

mtcars |> 
        split(mtcars$cyl) |> 
        lapply(sum) |>
        unsplit(mtcars$cyl)
```

