---
title: 'Advent Of Code: 2021-02'
author: Leo Carlsson
date: "`r Sys.Date()`"
output: html_document
---

```{r setup}
suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
  library(glue)
  
  knitr::opts_chunk$set(echo = TRUE)
})

options(scipen = 9999999)
options(dplyr.summarise.inform = FALSE)
```

--- Data ---

```{r eval = FALSE}
# tanho63/aoc.elf
aoc.elf::aoc_get(day = 2, year = 2021)
```

```{r}
input <- readLines(here::here("2021/day-02-input.txt"))
```

--- Part 1 ---

```{r}

input_df <- tibble(direction = input) %>% 
        separate(direction, into = c("direction", "distance"), sep = " ") %>% 
        mutate(distance = as.integer(distance))

output <- input_df %>% 
        group_by(direction) %>% 
        summarise(distance = sum(distance)) %>% 
        pivot_wider(names_from = direction, values_from = distance)

(output$down-output$up)*output$forward
```

--- Part 2 ---

```{r}
input_df
aim = 0
depth = 0
horizontal_position = 0

for (i in 1:length(input_df$distance)) {
        if(input_df$direction[i] == "down"){
                aim <-   aim+input_df$distance[i]
        }
        if(input_df$direction[i] == "up"){
                aim <-  aim-input_df$distance[i]
        }
        if(input_df$direction[i] == "forward"){
                horizontal_position <-  horizontal_position+input_df$distance[i]
                depth <- depth+(input_df$distance[i]*aim)
        }
}
depth*horizontal_position
```