---
title: 'Advent Of Code: 2021-09'
author: "Tan Ho"
date: "2021-12-09"
output: html_document
---

```{r setup}
suppressPackageStartupMessages({
        library(tidyverse)
        library(here)
        library(glue)
        library(tidygraph)
        knitr::opts_chunk$set(echo = TRUE)
})

options(scipen = 9999999)
options(dplyr.summarise.inform = FALSE)
```

--- Data ---

```{r eval = FALSE}
aoc.elf::aoc_get(9)
```

```{r}
input <- readLines(here::here("2021/2021/day-09-input.txt")) %>% 
        strsplit("") %>% 
        map(as.integer) %>% 
        unlist() %>% 
        matrix(ncol=100, byrow = TRUE)

example <- "2199943210,3987894921,9856789892,8767896789,9899965678" %>% 
        strsplit(",") %>% 
        `[[`(1) %>% 
        strsplit("") 

example <- example %>% 
        map(as.integer) %>% 
        unlist() %>% 
        matrix(ncol=10, byrow = TRUE) 

```


--- Part 1 ---

```{r}
check_adjecent <- function(element) {
        output_matrix <- matrix(nrow = nrow(element), ncol=ncol(element))
        for (row in 1:nrow(element)) {
                for (col in 1:ncol(element)) {
                        if (col == 1 & row==1) {
                                #First element, first row
                                right <- element[row, col + 1] > element[row, col]#element to the right
                                below <- element[row + 1, col] > element[row, col]#element below
                                test <- all(right, below)
                        } else if (col==1 & row != nrow(element)) {
                                #first column, every element but the last
                                right <- element[row, col + 1] > element[row, col] #element to the right
                                below <- element[row + 1, col] > element[row, col] #element below
                                above <- element[row - 1, col] > element[row, col] #element above
                                test <- all(right, below, above)
                        } else if (col == 1 & row == nrow(element)) {
                                #first element, last row
                                right <- element[row, col + 1] > element[row, col] #element to the right
                                above <- element[row - 1, col] > element[row, col] #element above 
                                test <- all(right, above)
                        } else if (row == 1 & col != ncol(element)) {
                                #first row, not last element
                                right <- element[row, col + 1] > element[row, col] #element to the right
                                left <- element[row,col - 1] > element[row, col] #element to the left
                                below <- element[row + 1, col] > element[row, col] #element below
                                test <- all(right, left, below)
                        } else if (row == 1 & col == ncol(element)) {
                                #last element of first row
                                left <- element[row,col - 1] > element[row, col] #element to the left
                                below <- element[row + 1, col] > element[row, col] #element below
                                test <- all(left, below)
                        } else if (row == nrow(element) & col == ncol(element)) {
                                #last element of last row
                                above <- element[row - 1, col] > element[row, col] #element above 
                                left <- element[row,col - 1] > element[row, col] #element to the left
                                test <- all(above, left)
                        } else if (col == ncol(element) & row != 1 & row != nrow(element)) {
                                #last col
                                above <- element[row-1, col] > element[row, col] #element above 
                                below <- element[row+1, col] > element[row, col] #element below
                                left <- element[row,col-1] > element[row, col] #element to the left
                                test <- all(above, below, left)
                        } else if (row == nrow(element) & col != 1 & col != ncol(element)) {
                                #last row
                                above <- element[row-1, col] > element[row, col] #element above 
                                left <- element[row,col-1] > element[row, col] #element to the left
                                right <- element[row, col+1] > element[row, col] #element to the right
                                test <- all(above, left, right)
                        } else {
                                #non-edge numbers
                                right <- element[row, col+1] > element[row, col] #element to the right
                                left <- element[row,col-1] > element[row, col] #element to the left
                                below <- element[row+1, col] > element[row, col] #element below
                                above <- element[row-1, col] > element[row, col] #element above 
                                test <- all(right, left, below, above)
                        }
                        output_matrix[row, col] <-  test
                }
        }
        output_matrix
}

filter<- check_adjecent(example)
res <- example[filter]
sum(res+1)
```
480
--- Part 2 ---

```{r}
tg <- tibble(x=input) %>% 
        mutate(row = row_number(),
               value = str_split(x, "")) %>% 
        unnest(value) %>% 
        select(-x) %>% 
        group_by(row) %>% 
        mutate(col = row_number())


basins <- create_lattice(c(100, 100), directed = TRUE, mutual = TRUE) %>% 
        mutate(!!!tg) %>% 
        filter(value != 9) %>% 
        mutate(basin = group_components()) %>% 
        as_tibble()
basins %>% 
        count(basin, sort = TRUE) %>% 
        slice_min(basin, n=3, with_ties = FALSE) %>% 
        pull(n) %>% 
        prod()

basins %>% 
        ggplot(aes(col, row)) +
        geom_point(aes(color = basin)) +
        scale_y_reverse() +
        scale_x_continuous(position = "top") +
        coord_equal()
```


