---
title: 'Advent Of Code: 2021-01'
author: Leo Carlsson
date: "`r Sys.Date()`"
output: html_document
---

```{r setup}
suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
  library(glue)
  
  knitr::opts_chunk$set(echo = TRUE)
})

options(scipen = 9999999)
options(dplyr.summarise.inform = FALSE)
```

--- Data ---
```{r eval = FALSE}
# tanho63/aoc.elf
aoc.elf::aoc_get(day = 1, year = 2021)
```

```{r}
input <- readLines(here::here("2021/day-01-input.txt"))
```

--- Part 1 ---
```{r}

output <- c()
for (n in 1:length(input)) {
        result <- input[n] < input[n+1]
        output <- c(output, result)
}
output
sum(output, na.rm = T)
```

--- Part 2 ---

```{r}
library(slider)
input <- tibble(values = as.integer(input)) %>% 
        mutate(value2 = slide_sum(values, before = 2,
                                  complete = TRUE)) %>% 
        filter(!is.na(value2)) %>% 
        pull(value2)

output <- c()
for (n in 1:length(input)) {
        result <- input[n] < input[n+1]
        output <- c(output, result)
}
sum(output, na.rm = T)
```

