---
title: 'Advent Of Code: 2021-15'
author: Leo Carlsson
date: "`r Sys.Date()`"
output: html_document
---

```{r setup}
suppressPackageStartupMessages({
        library(tidyverse)
        library(here)
        library(glue)
        library(adventdrob)
        library(tidygraph)
        knitr::opts_chunk$set(echo = TRUE)
})

options(scipen = 9999999)
options(dplyr.summarise.inform = FALSE)
```

--- Data ---

```{r eval = FALSE}
aoc.elf::aoc_get(day = 15, year = 2021)
```

```{r}
input <- readLines(here::here("2021/day-15-input.txt"))
```

--- Part 1 ---
```{r}
grid_tidy <- function(d, var, sep = "", parse = TRUE) {
        ret <- d %>%
                mutate(row = row_number()) %>%
                mutate(value = stringr::str_split({{ var }}, sep)) %>%
                select(-{{ var }}) %>%
                tidyr::unnest(value) %>%
                group_by(row) %>%
                mutate(col = row_number()) %>%
                ungroup()

        if (parse) {
                ret <- ret %>%
                        mutate(value = parse_txt(value))
        }

        ret
}


grid_graph <- function(d, ..., directed = FALSE,
                       mutual = FALSE, circular = FALSE) {
        td <- grid_tidy(d, ...)
        dimensions <- c(max(td$row), max(td$col))

        tidygraph::create_lattice(dimensions,
                                  directed = directed,
                                  mutual = mutual,
                                  circular = circular) %>%
                mutate(!!!td)
}
```

```{r}
td <- tibble(x = input) |> 
        mutate(row = row_number()) |> 
        mutate(value = stringr::str_split(x, "")) |> 
        select(-x) |> 
        tidyr::unnest(value) |> 
        group_by(row) |> 
        mutate(col = row_number()) |> 
        ungroup()

td
dimensions <- c(max(td$row), max(td$col))
```

```{r}
tg <- tidygraph::create_lattice(dimensions,
                                directed = TRUE,
                                mutual = TRUE) %>%
        mutate(!!!td)
tg <- tg %>%
        activate("edges") %>%
        mutate(risk = .N()$value[to])
```

```{r}
tg %>%
        activate("nodes") %>%
        convert(to_shortest_path, from = 1, to = 10000, weights = risk) %>%
        activate("edges") %>%
        pull(risk) %>%
        as.integer() %>%
        sum()

tg %>%
        activate("nodes") %>%
        convert(to_shortest_path, from = 1, to = 10000, weights = risk) %>%
        activate("nodes") %>%
        as_tibble() %>%
        ggplot(aes(row, col)) +
        geom_line() +
        scale_y_reverse() +
        scale_x_continuous(position = "top") +
        coord_fixed()
```

--- Part 2 ---

```{r}

```





